version: '3.8'

services:
  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - aluuna-network

  # Production service
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - aluuna-network
    depends_on:
      - app-dev

  # Optional: Add a database service if needed later
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: aluuna
  #     POSTGRES_USER: aluuna_user
  #     POSTGRES_PASSWORD: aluuna_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - aluuna-network

networks:
  aluuna-network:
    driver: bridge

# volumes:
#   postgres_data:
